export const SEARCH_MOVIE_START = 'SEARCH START';
export const SEARCH_MOVIE_ERROR = 'SEARCH ERROR';
export const SEARCH_MOVIE_COMPLETE = 'SEARCH COMPLETE';

export const SearchActionByMovieTypes = {
    SEARCH_MOVIE_ID_START: 'SEARCH MOVIE ID START',
    SEARCH_MOVIE_ID_ERROR: 'SEARCH MOVIE ID ERROR',
    SEARCH_MOVIE_ID_COMPLETE: 'SEARCH MOVIE ID COMPLETE',
}